name: Monitor Imóveis

on:
  schedule:
    # Executar a cada 30 minutos (você pode ajustar)
    - cron: '*/30 * * * *'
  workflow_dispatch:  # Permite execução manual através do GitHub

  # Adicione esta seção de permissões
permissions:
  contents: write

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Necessário para poder fazer commit depois
      
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 python-telegram-bot==13.7 schedule
          
      - name: Executar verificação de imóveis
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          SITES_IMOBILIARIAS: ${{ secrets.SITES_IMOBILIARIAS }}
        run: python bot_imoveis.py
        
      - name: Commit de alterações (salvar estado)
        if: success()
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add paginas_hashes.json notificacoes.txt || true
          git diff --staged --quiet || git commit -m "Atualizar estado após verificação"
          git push
