name: Monitor Imóveis

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Verificar diretório de trabalho
        run: |
          echo "Diretório de trabalho: $PWD"
          echo "Conteúdo do diretório:"
          ls -la
      
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 python-telegram-bot==13.7
          
      - name: Executar verificação de imóveis
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          SITES_IMOBILIARIAS: ${{ secrets.SITES_IMOBILIARIAS }}
        run: python bot_imoveis.py
      
      - name: Verificar arquivos gerados
        run: |
          echo "Verificando arquivos após execução:"
          ls -la
          if [ -f "paginas_hashes.json" ]; then
            echo "✅ Arquivo de hashes encontrado"
            cat paginas_hashes.json | head -20  # Mostra as primeiras 20 linhas
          else
            echo "❌ Arquivo de hashes NÃO encontrado!"
          fi
        
      - name: Commit de alterações
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Garantir que o arquivo existe, mesmo que vazio
          if [ ! -f "paginas_hashes.json" ]; then
            echo "{}" > paginas_hashes.json
          fi
          
          # Adicionar arquivos para commit
          git add paginas_hashes.json
          [ -f "notificacoes.txt" ] && git add notificacoes.txt
          
          # Verificar se há mudanças e fazer commit
          if git diff --staged --quiet; then
            echo "Nenhuma mudança para commit"
          else
            git commit -m "Atualizar estado após verificação em $(date)"
            git push
          fi
